[package]
name = "axvmconfig"
version = "0.1.0"
edition = "2021"
description = "A simple VM configuration tool for ArceOS-Hypervisor."

[features]
default = ["std"]
std = ["dep:clap"]

[dependencies]
env_logger = "0.11.3"
log = "0.4.21"
serde = { version = "1.0.204", default-features = false, features = ["derive"] }
serde_repr = "0.1"
toml = { git = "https://github.com/arceos-hypervisor/toml.git", branch = "no_std" }
axerrno = "0.1.0"

clap = { version = "4.5.23", optional = true, features = ["derive"]}
